#!/bin/sh
#
# ncsa-cert-retrieve
#
# wrapper script that calls ncsa-cert-retrieve.pl with a perl executable
#

if [ "$GLOBUS_LOCATION" = "" ]; then
  echo "Set GLOBUS_LOCATION before running this script"
  exit 1
fi

perl $GLOBUS_LOCATION/bin/ncsa-cert-retrieve.pl $*

